### ISSUE TITLE
fix: make "County" field not required.

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4316] opened 2019-12-03 18:06 UTC
# Bug Report

## User Story

As a user, I want to make the "county" field not required so that donors don't have to fill that information in order to make a donation.

This bug only happens if the Base Country is set to "United Kingdom" so If I'm a UK user and I need to collect billing information I don't want my UK donors to have to fill a supposedly unrequired field.

## Current Behavior

If the billing country is set to "United Kingdom",  you will also see a "County" field that is not marked as required but the form will not process if the field is left empty.

## Expected Behavior

The form should process to payment without "county" information since it's not marked as required.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
To reproduce with only Give core.
1. Set the Base Country to United Kingdom
2. In Stripe settings, enable "Collect Billing Details" and set Stripe as the default payment gateway.
On the front end of the form, do not change the billing country, leave it set to "United Kingdom",  you will also see a "County" field that is not marked as required but the form will not process if the field is left empty.

## Visuals

http://somup.com/cqleFcfuy8

## Possible Solution

A couple of not-so-fancy workarounds
1. Use a different default payment gateway other than Stripe if possible.
2. Don't collect billing details if in the UK

## Related

https://secure.helpscout.net/conversation/1018231466/51855/ https://secure.helpscout.net/conversation/1015727995/51538/

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

### GiveWP Configuration ###

GiveWP Version: 2.5.10
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givecore.local/donation-confirmation/
Failure Page: http://givecore.local/donation-failed/
Donation History Page: http://givecore.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card, PayPal Standard
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

**Comment by DevinWalker** [comment] 2019-12-03 18:55
Thanks for reporting @rickalday - we'll get this fixed in the next release.

**Comment by henryholtgeerts** [comment] 2019-12-04 16:52
Successfully reproduced the issue this morning. Appears to be a problem in includes/forms/template.php. Ruled out form validation issue, and the form works correctly when loaded over ajax (if you select another country, then go back to UK).

**Comment by henryholtgeerts** [comment] 2019-12-04 17:27
Further testing revealed that this bug is true of **all** countries where the state field is denoted as not required in give_states_list(). 

After poking around, it looks like includes/forms/template.php is using separate logic to determine if asterisk is displayed vs. is field is actually marked required. Attempting to resolve now.

**Closed** 2019-12-06 15:43 UTC
