### ISSUE TITLE
A donor should view a donation receipt from a subscription list

### ISSUE THREAD

**Issue by Genevieve-K** [impress-org/givewp#6722] opened 2023-03-07 11:56 UTC
## User Story

As a donor, I want to see my donation receipt from a subscription list.

If I click on View Receipt, I stay in the 'Recurring Donations' page.

## Steps to Reproduce

1. Go to  the 'Recurring Donations' page.
2. Click on View Receipt
3. The link contains 'recurring-donations' and not 'donation-history', and the page is not found.

## Code

In 1.15.0:
`<a href="<?php echo give_get_receipt_url( $subscription->parent_payment_id ); ?>">`

In 2.3.0: 
` echo  esc_url(
                        add_query_arg(
                            'donation_id',
                            $subscription->parent_payment_id,
                            $_SERVER['REQUEST_URI']
                        )`
The URL is built from the current URL, with  'recurring-donations'.

**Comment by kjohnson** [comment] 2023-03-07 15:27
Hey @Genevieve-K, thanks for the bug report.

It looks like this is a regression since moving towards the Donor Dashboard. The location returned by `give_get_receipt_url()` was co-opted by the Donor Dashboard, which unexpected behavior in context of the Subscriptions shortcode. When we adjusted the Subscriptions shortcode to update the link we should have used `give_get_history_page_uri()` to restore the previous functionality.

I've created a related issue in the Give Recurring (private) repo which is linked for the team's reference above.

**Comment by kjohnson** [comment] 2023-03-10 14:26
@Genevieve-K if you reach out to support (tell them that I sent you) and mention this issue then I can get you a pre-release of the recurring add-on with this fixed.

**Comment by Genevieve-K** [comment] 2023-03-22 10:54
@kjohnson I submit this request. The answer is: The best way here is to nudge the developed on Github so he can get back to you about it. Could you send me the code with this correction?

**Comment by JoshuaHungDinh** [comment] 2023-05-07 16:28
This issues has been completed: https://github.com/impress-org/give-recurring/pull/1122 & [Links on the [donation_history] to view the receipt should not load the donor dashboard](https://givewp.canny.io/admin/board/bug-reports/p/links-on-the-donationhistory-to-view-the-receipt-should-not-load-the-donor-dashb)

**Closed by JoshuaHungDinh** 2023-05-07 16:28 UTC
Labels: type: bug, keep-fresh

**Comment by Genevieve-K** [comment] 2023-07-31 20:41
@kjohnson @JoshuaHungDinh I allow myself to come back on this subject. Failing to have the fix, I kept my correction in shortcode-subscriptions.php. 
Today I installed Give Recurring 2.4.3, I don't see this correction, and if I click on 'View Receipt' in a subscription list, T stay on ths page. The link is ../recurring-donations/?donation_id=2047 and not .../donation-history/?donation_id=2047
So I make the correction in this version 2.4.3

**Comment by Genevieve-K** [comment] 2025-02-17 19:46
Hi. I just installed Give Recurring version 2.11.1. It's not fixed.
As a donor, I get the page Recurring donation history without Dashboard. All my subscriptions are displayed. If I click on "View Receipt", the same page with the list is displayed?

**Comment by jonwaldstein** [comment] 2025-02-20 19:44
Hey @Genevieve-K thanks for reaching out.  I'll bring this back up with the team and see what they say 😄
