### ISSUE TITLE
Reports should show accurate numbers for different currencies

### ISSUE THREAD

**Issue by jurassicdanie** [impress-org/givewp#4796] opened 2020-06-09 19:08 UTC
# Bug Report

## User Story
As a user, I want to be able to pull up the Reports in GiveWP and see accurate numbers from different currencies listed.

## Details
To better explain this, when you go to Donations -> Reports and you look around at the reports, on the bottom left side, it shows your total donations with the different currencies, which is correct. Directly to the right of that, under "Top Donors" different currencies show up as USD, not what the converted amount would be.

## Current Behavior
Currently in the Reports section, it shows the different currencies with their donations, however, it doesn't actually convert it. So for example (I will attach a screenshot), I did a test donation is $50 USD, and then two in 5 Euros and one in 10 Euros. Under the Top Donors section, it shows that I donated a total of $70 USD, instead of the $72.69 it should have been with the conversion.

## Expected Behavior
You should be able to view the Reports and have an area where it shows what all amounts you receive and in what currency (which it does) and also the correct converted amount for the total of all donations.

## Bug Type

- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Make donations in multiple currencies
2. Go to Donations
3. Go to Reports

## Visuals
![2020-06-09_1504](https://user-images.githubusercontent.com/63911898/84189174-d4af5a00-aa62-11ea-8e0d-3e6f74000e52.png)

## Related
Ticket: https://secure.helpscout.net/conversation/1188265345/67337?folderId=3805719

## Acceptance Criteria
Have currencies show correctly in Reports

## Environment
This occurs on all systems/environments

**Comment by DevinWalker** [comment] 2020-06-09 19:09
Closing as duplicate of https://github.com/impress-org/givewp/issues/4542

**Closed by DevinWalker** 2020-06-09 19:09 UTC
