### ISSUE TITLE
fix: adjust zip code requirement based on country

### ISSUE THREAD

**Issue by samsmith89** [impress-org/givewp#3945] opened 2019-01-16 15:30 UTC
# Bug Report

## User Story

As a site admin, I want the zip code field to disable or remove the requirement when Hong Kong is the city that is input so that the donation can process.

There is no zip code for the cities Hong Kong or Macau.
https://www.travelchinaguide.com/essential/area_zip/

## Current Behavior

Currently, if a donor inputs the billing details they must enter a zip code for the donation to process.

## Expected Behavior

I expect the zip code field to either disable or remove the requirement whenever Hong Kong is entered into the city field.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

### With Stripe Checkout Disabled

1. Complete the billing details with Hong Kong as the country, Hong Kong as the city, and Hong Kong Island as the region.
2. Do not enter a zip code.
3. See that the zip code field will prevent the donation from submitting because the browsers is trying to validate a required field.

### With Stripe Checkout Enabled

1. Create a new donation and trigger the Stripe Checkout modal.
2. Change the country to Hong Kong and note that the postal code field disappears in the Stripe Checkout modal.
3. Complete the rest of the donation. You should see a green checkmark indicating that the donation was submitted, however a red error will appear that says `Please enter your postcode`.

## Visuals

![screen shot 2019-01-16 at 10 25 33 am](https://user-images.githubusercontent.com/20672471/51258928-17a5f480-1979-11e9-9f70-76773959357c.png)

## Possible Solution

Add a conditional JS event listener that runs when China is selected, that will toggle the requirement and display on the zip code field attributes when the City is == to Hong Kong || hong kong.

## Related

https://secure.helpscout.net/conversation/755719619/32716/

## Acceptance Criteria

- [ ] When Stripe Checkout is ENABLED and billing details are enabled, donors from Hong Kong can submit a donation without having to put in a zip code.
- [ ] When Stripe Checkout is DISABLED and billing details are enabled, donors from Hong Kong can submit a donation without having to put in a zip code.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, acf-disabled, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.1
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.3.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Authorize.net
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Annual Receipts: ❌ Unlicensed – by GiveWP – 1.0.0
Give - Authorize.net Gateway: ❌ Unlicensed – by GiveWP – 1.4.4
Give - Braintree Gateway: ❌ Unlicensed – by GiveWP – 1.2.3
Give - CCAvenue Gateway: ❌ Unlicensed – by GiveWP – 1.0.4
Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by GiveWP – 1.1.0
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 1.7.4
Give - Form Countdown: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by GiveWP – 1.2.1
Give - MailChimp: ❌ Unlicensed – by GiveWP – 1.4.3
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.2
Give - PayPal Pro Gateway: ❌ Unlicensed – by GiveWP – 1.2.1
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0.1
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.2
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.2
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.2
Give - Tributes: ❌ Unlicensed – by GiveWP – 1.5.2
Sam's Helper Function: ❌ Unlicensed – by WordImpress – 1.0

### Other Active Plugins ###

Advanced Custom Fields: by Elliot Condon – 5.7.7
Give - Hook Helper: by Ravinder Kumar – 1.0
Notification: by BracketSpace – 5.3.2
Transients Manager: by Pippin Williamson – 1.7.5
User Role Editor: by Vladimir Garagulya – 4.47
WP Business Reviews: by Impress.org – 1.2.0

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 6.78
Contact Form 7: by Takayuki Miyoshi – 5.0.4
Elementor: by Elementor.com – 2.3.2
Give - Email Reports: by WordImpress – 1.1.2
Give - Gift Aid: by WordImpress – 1.1.6
Give - GoCardless Gateway: by WordImpress – 1.2.1
Give - Mollie Gateway: by WordImpress – 1.1.2
Give - Razorpay: by WordImpress – 1.2.0
Gutenberg: by Gutenberg Team – 4.1.1
Intelligence: by LevelTen – 1.3.1
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
WooCommerce: by Automattic – 3.5.2
WordPress Importer: by wordpressdotorg – 0.6.4

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by samsmith89** [comment] 2019-01-16 15:31
@kevinwhoffman I'm happy to work on this if you see fit.

**Comment by kevinwhoffman** [comment] 2019-01-16 19:30
@samsmith89 We need to consider both client-side validation (which your example shows) and server-side validation (which the customer shows in their attached screenshot).

## Client-side Validation (Stripe Checkout disabled)

- In Give, this occurs when a form input has a `required` attribute and does not let the form process until all required fields are populated.
- In Stripe, this applies when the billing address fields are in the main donation form because Stripe Checkout is not enabled.

## Server-side validation (Stripe Checkout enabled)

- In Give, this occurs when a form is submitted but does not pass validation according to the conditions defined in PHP.
- In Stripe, this applies when the billing address fields are NOT in the main donation form because Stripe Checkout is enabled.

## Video

This screencast shows issues with both client-side and server-side validation whenever a zip code is not provided.

https://www.useloom.com/share/1b8b2017a1e44f489f5a87c06561d4f1

**Comment by kevinwhoffman** [comment] 2019-01-16 20:43
## Slack Call Summary

Participants: @samsmith89 @kevinwhoffman 
Topic: How to reproduce and work around the zip code requirement error
Result: Kevin and Sam recreated the error with Stripe checkout enabled and disabled. We also tested the filter that Sam provided to the customer and confirmed that it does solve the issue and allow Hong Kong donations to be processed correctly.

## Temporary Workaround

```php
function give_dont_require_fields( $required_fields, $form_id ) {
	if(isset($required_fields['card_zip'])) {
		unset($required_fields['card_zip']);
	}
	return $required_fields;
}
add_filter( 'give_donation_form_required_fields', 'give_dont_require_fields', 10, 2 );
```

## Possible Solution

We should investigate whether there are other values for the `Country` dropdown besides `Hong Kong` that do not use postal codes and see if we can automatically remove the postal code requirement based on the selected country.

The solution will probably require both JS and PHP to account for the postal code field in the Give form and on the server.

**Comment by kevinwhoffman** [comment] 2019-01-29 05:57
@nishitlangaliya Please research whether there are any other countries or cities that do not have zip codes so that we can make the zip code not required in those circumstances.

If you identify any others besides Hong Kong, please report them in this issue. Then discuss with @ravinderk about the best way to remove the zip code requirement within the form. I think it will require a JS event listener that uses the currently selected country to determine the requirement.

**Comment by nishitlangaliya** [comment] 2019-01-29 10:24
@kevinwhoffman I found below listed countries have no zip code available.
`Angola
Antigua and Barbuda
Aruba
Bahamas
Belize
Benin
Botswana
Bolivia
Burkina Faso
Burundi
Cameroon
Central African Republic
Comoros
Congo
Congo the Democratic Republic of the
Cook Islands
Djibouti
Dominica
Equatorial Guinea
Eritrea
Fiji
French Southern and Antarctic Lands
Gambia
Ghana
Grenada
Guyana
Hong Kong
Kiribati
Macau
Malawi
Mali
Mauritania
Nauru
Niue
North Korea
Qatar
Rwanda
south africa
Saint Kitts and Nevis
Sao Tome and Principe
Seychelles
Sierra Leone
Solomon Islands
Suriname
Syria
Timor-Leste
Tokelau
Tonga
Tuvalu
Uganda
United Arab Emirates
Vanuatu
Yemen`

**Comment by kevinwhoffman** [comment] 2019-01-30 06:36
@mehul0810 assigning this to your sprint backlog when you get to Stripe issues.

Please review the issue as I have described it in https://github.com/impress-org/give/issues/3945#issuecomment-454908883. I was not able to complete a donation with or without Stripe checkout enabled because of the zip code requirement for locations like Hong Kong which do not have zip codes. That is the issue that needs addressed, along with any other locations which may not require zip codes.

**Comment by nishitlangaliya** [comment] 2019-01-31 11:01
@kevinwhoffman , I have gone through both scenario as mentioned in https://github.com/impress-org/give/issues/3945#issuecomment-454908883 and tried to reproduce issue but unable to reproduce issue. I am able to do successfully donation in both case like enable stripe checkout and disabled stripe checkout with country like Hong Kong which has no zip code. Below is my testing video:

https://www.useloom.com/share/d1d90761004f4de4a0d2e2bd9d6b3e2f 

Thanks

**Comment by mehul0810** [comment] 2019-02-01 12:31
@kevinwhoffman I've tried replicating this issue with/out Stripe Checkout using `master` as well as `release/2.2.0` branch and unable to reproduce the issue. Also, I've tried to replicate the instance same as mentioned in the System Info and still unable to reproduce. 

Can you provide me your system info in which you've reproduced the issue?

**Comment by DevinWalker** [comment] 2019-05-08 17:47
I'm going to be testing this one to verify it's an issue still.

**Comment by mikejhale** [comment] 2019-10-02 20:11
@mehul0810 Can you look into this and confirm if this still occurs?

**Comment by mehul0810** [comment] 2019-10-04 06:22
@mikejhale I can reproduce this issue. I can see that when you select `Macau` or `HongKong as the country and then see that the "Postal Code" field exists and is always required. But, when I checked code it seems that there is no logic implemented for the same. So, if we decide to fix this issue then it will be a feature not a bug fix.

**Comment by allienimmons** [comment] 2020-01-09 14:58
@DevinWalker Another customer has written in about this: https://secure.helpscout.net/conversation/1034777306/0/?folderId=3046394

**Comment by rickalday** [comment] 2020-05-07 02:32
https://secure.helpscout.net/conversation/1143855530/63362/

**Comment by kevinwhoffman** [comment] 2020-07-20 03:05
Moving to Canny with the priority support feedback so that we can better track the impact: https://givewp.canny.io/bug-reports/p/postal-codes-should-not-be-required-for-some-countries

**Closed by kevinwhoffman** 2020-07-20 03:05 UTC
