### ISSUE TITLE
Legacy reports filtering should load data instead of redirecting users

### ISSUE THREAD

**Issue by matheuswd** [impress-org/givewp#4827] opened 2020-06-18 16:37 UTC
# Bug Report

## User Story

As a site admin, I want to check the legacy reports **and** filter my results.

## Current Behavior

When I click to filter my results, I'm redirected to the Reports page (the new one)

## Expected Behavior

I need to be able to filter my results on the legacy reports page.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Make sure you have donations on your GiveWP install (Donations > Donations)
2. Access Donations > Reports > Income
3. Select a filter and click on Filter

## Visuals

![Screen Recording 2020-06-18 at 17 33 24](https://user-images.githubusercontent.com/11727852/85047700-1c806080-b18a-11ea-9b64-f322e9ad9aa2.gif)

## Acceptance Criteria

- [ ] site administrator should be able to filter donations using legacy reports

### WordPress Environment ###

Home URL: https://givedemo.test
Site URL: https://givedemo.test
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home (#4)
Page for Posts: Unset
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givedemo.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.43 (Unix)
PHP Version: 5.6.39
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.54.0, LibreSSL/2.6.5
SUHOSIN Installed: –
MySQL Version: 5.7.28
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ❌New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions❌New User Registration✔User Registration Information✔Donation Note✔Email access❌Daily Email Report❌Weekly Email Report❌Monthly Email Report✔Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.6.3
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://givedemo.test/thank-you-for-your-donation/
Failure Page: https://givedemo.test/donation-failed/
Donation History Page: https://givedemo.test/my-giving-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Authorize.net, PayPal Standard, Authorize.net eCheck (ACH), Offline Donation
Default Payment Gateway: Authorize.net
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: June 11, 2020 1:36 am
Square Token Renewal Date: N/A

### Active GiveWP Add-ons ###

Give - Annual Receipts: ❌ Unlicensed – by GiveWP – 1.0.2
Give - Authorize.net Gateway: ❌ Unlicensed – by GiveWP – 1.4.6
Give - Currency Switcher: ❌ Unlicensed – by GiveWP – 1.3.7
Give - Email Reports: ❌ Unlicensed – by GiveWP – 1.1.4
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 1.7.8
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.6
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.8
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.10.2
Give - Square: ❌ Unlicensed – by GiveWP – 1.1.1
Give - Tributes: ❌ Unlicensed – by GiveWP – 1.5.6

### Other Active Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.6
Elementor: by Elementor.com – 2.9.12
Elementor Pro: by Elementor.com – 2.10.1
Instant Images: by Darren Cooney – 4.3.2
Starter Templates: by Brainstorm Force – 2.3.0
WPForms Lite: by WPForms – 1.6.0.2
WP Migrate DB Pro: by Delicious Brains – 1.9.10
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.15
WP Migrate DB Pro Theme & Plugin Files: by Delicious Brains – 1.0.5

### Inactive Plugins ###

Pixabay Images: by Simon Steinberger – 3.4

### Active MU Plugins ###

WP Migrate DB Pro Compatibility: by Delicious Brains – 1.2

### Theme ###

Name: give-demo
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: Yes
Parent Theme Name: Astra
Parent Theme Version: 2.3.5
Parent Theme Author URL: https://wpastra.com/about/

**Comment by henryholtgeerts** [comment] 2020-06-23 21:37
In my own testing, I am unable to reproduce this issue using GiveWP 2.7.0. This particular issue has been raised previously, and was addressed and tested in release 2.6.3 (see: https://github.com/impress-org/givewp/pull/4645). 

@ravinderk Are you able to reproduce this error?

**Comment by henryholtgeerts** [comment] 2020-06-24 19:54
Update: I have been able to reproduce this error using an export of @matheuswd's  Local installation. Also tested using the provided Local installation using the latest work on the `release/2.7.0` branch and the issue persisted. I'm investigating it now!

**Comment by henryholtgeerts** [comment] 2020-06-24 20:24
After looking into it, this issue is caused by the version of Give Fee Recovery that @matheuswd was running alongside Give 2.7.0. This issue was resolved in Give Fee Recovery release 1.7.9 (see merged PR: https://github.com/impress-org/give-fee-recovery/pull/268), and does not occur on websites running Give Fee Recovery 1.7.9 or later. Because Give Fee Recovery 1.7.11 is the listed requirement to run with GiveWP 2.7.0, I'm going to move forward with closing this issue.

**Closed by henryholtgeerts** 2020-06-24 20:24 UTC
