### ISSUE TITLE
fix: Reports do not account for currency exchange rate

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4568] opened 2020-03-20 00:22 UTC
# Bug Report

## User Story

As an admin, I want to see reports for the different currencies I use on my site.

## Current Behavior

The reports show the same amounts even if I change the base currency.

## Expected Behavior

Reports should show the correct amounts based on the selected base currency taking into consideration the exchange rate.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install the Currency Switcher add-on and add one or more currencies
2. Create a few donations in different currencies
3. Check reports page
4.  Change base currency
5. Check reports page again

## Visuals

<img width="1173" alt="Screen Shot 2020-03-19 at 6 08 38 PM" src="https://user-images.githubusercontent.com/312000/77126353-697b5c00-6a0e-11ea-83af-54c4c149c696.png">

## Related

https://secure.helpscout.net/conversation/1114182722/60194/

## Acceptance Criteria

- [ ] Reports show correct amounts based on currency exchange rates

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by DevinWalker** [comment] 2020-03-20 00:24
Closing as a duplicate of: https://github.com/impress-org/givewp/issues/4542

**Closed by DevinWalker** 2020-03-20 00:24 UTC
