### ISSUE TITLE
fix: resolve conflict with Contact Form 7 and Currency Switcher

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4241] opened 2019-08-21 19:35 UTC
# Bug Report

## User Story

As a user, I want to be able to open a donation form and toggle between payment gateways, with both the Contact Form 7 and Currency Switcher plugins installed, without the CC fields collapsing so that I don't believe something is broken on the form.

## Current Behavior
Currently, when both Currency Switcher and Contact Form 7 plugins are installed, there is an unexpected activity happening where, if the user chooses PayPal as a Gateway, then chooses Stripe, the credit card fields will collapse. On a mobile device, they will disappear altogether. If either one - Currency Switcher or Contact Form 7 - are disabled, this action doesn't happen.

I tried to mimic the exact environment and settings they had and I wasn't able to replicate it that way. The only way I could do it was to do an export of their Give settings to my own. Then it broke in the way that they were seeing. I went back into my settings and reset everything to match a local site I have that does NOT break. I cannot get it to UNbreak. 

The export file I used is attached here.

## Expected Behavior
The expected behavior is for no change to take place with the credit card form styling.
 
## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install Currency Switcher, Give Core and Contact Form 7 
2. Set up PayPal Standard and Stripe (Free)
3. Create a form with both gateway options enabled, Stripe as the default
4. Choose PayPal, then choose Stripe

## Visuals
<img width="857" alt="Screen Shot 2019-08-21 at 3 30 48 PM" src="https://user-images.githubusercontent.com/41754561/63462511-1c5beb00-c429-11e9-8eaf-9be293e5169f.png">

## Related
https://secure.helpscout.net/conversation/928735147/45180?folderId=672201

## Acceptance Criteria

- [ ] Toggling between gateways with Contact Form 7 and Currency Switcher enabled causes no change to the form fields.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

[Export File.zip](https://github.com/impress-org/givewp/files/3535678/Export.File.zip)

**Comment by allienimmons** [comment] 2019-10-03 17:29
[45180 export.zip](https://github.com/impress-org/givewp/files/3687323/45180.export.zip)

**Comment by mehul0810** [comment] 2019-10-21 08:48
@mikejhale I've researched this issue and I'm unable to reproduce this issue. I've tried it with Contact Form 7 plugin in combination with Contact Form 7 - PayPal & Stripe add-on. But, It seems that this issue is older and not reproduced with latest Give. I believe that this issue arose before we introduced Stripe SDK loading admin settings.

Let me know your thoughts.

**Comment by Benunc** [comment] 2019-12-16 16:57
Closing until we can reliably replicate. I touched base with the customer.

**Closed by Benunc** 2019-12-16 16:57 UTC
Labels: needs-confirmation
