### ISSUE TITLE
fix: investigate donor email conflicts

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#3931] opened 2019-01-09 17:47 UTC
# Bug Report

## User Story

As a donor, I want to make a successful logged-out donation even if I already have a WP user account so that I'm not frustrated when trying to donate.

## Scenarios

Let's use this issue to document different scenarios that may or may not trigger an email conflict. Be sure to enter the steps to recreate and ideally attach a screencast.

**Comment by kevinwhoffman** [comment] 2019-01-09 17:48
## Steps Tested

1. Have a recurring form, and enable the account creation feature so that WP Users are created automatically when creating a recurring donation.
2. Do a recurring donation while logged out.
3. Confirm that it created the donor profile, and a WP User profile, and those two are correctly associated with each other
4. Do another one-time donation while logged out with the SAME email address
5. What are the results?
6. Do another recurring donation while logged out with the SAME email address
7. What are the results?

## Result

No email errors or conflicts were generated.

https://www.useloom.com/share/5831fe74239b46069b45cb880a5492bf

**Comment by kevinwhoffman** [comment] 2019-01-09 18:04
## Scenario 2

1. Create a new WP user with email matt@example.com.
2. Attempt do donate while logged out with matt@example.com as the email.
3. Note the error `Email already exists`.

## Result

- The error occurs when a logged-out user attempts to donate AND create a new account using an email already associated with a WP user.
- Unchecking the box to create a new account allows the donation to succeed. A new donor is created with the same email address as the WP user, however the WP user is not automatically associated with the new donor.

https://www.useloom.com/share/5693f0275f534d63b816708faee8d554

**Comment by kevinwhoffman** [comment] 2019-01-10 04:58
@DevinWalker @mathetos Please review Scenario 2 above so we can discuss how to better handle or avoid the error altogether.

**Comment by mathetos** [comment] 2019-01-10 19:43
Without seeing the code that creates that error, I would hope/expect that the donation creation process would be able to:

1. check whether the user exists
2. If it exists, skip the user creation process, complete the donation with donor profile created, then associate the new donor profile with the existing WP User
3. If it doesn't exist, then the donation continues as normal as it does today.

I don't think it's right for us to prevent donations simply because there is an existing WP User account, that feels like a serious bug or unintended behavior.

**Comment by DevinWalker** [comment] 2020-07-22 18:32
A few findings here:

1. Unchecking the `Create account` checkbox allows the donation to process and associates the donation with the users email. This means the donation is still allowed to process.
2. This is an edge case and no customer have reported that I have seen.
3. The user can log in to donate as well, therefore they're not blocked in another way from giving.

Seeing that this is more than a year old and isn't a significant issue or isn't a real bug I elect to close this out.

**Closed by DevinWalker** 2020-07-22 18:32 UTC
Labels: needs: triage
